// ---------------------------------------------------------------------------
// SH-405 ingestion pipeline — Raw Dataset → Schema Mapping / Cleaning →
// SH-405 Canonical Dataset. Pure Node (no dependencies), so it can run as a
// build step and be unit-tested with `node --test`.
//
// Input : source_data/set100/csv/*.csv  (public SYNTHETIC Synthea export)
// Output: canonical SH-405 dataset (patients, clinical, longitudinal records)
//
// Synthea is a synthetic-data generator: all records are fabricated, so no
// real patient/PHI is used anywhere in this pipeline.
// ---------------------------------------------------------------------------

import fs from 'node:fs'
import path from 'node:path'

export const CANONICAL_SCHEMA_VERSION = 'sh405-canonical-1'

// LOINC codes we normalize from the Synthea observations table.
export const VITAL_CODES = {
  '8480-6': 'systolic_bp',
  '8462-4': 'diastolic_bp',
  '72514-3': 'pain_score',
  '2339-0': 'glucose',
  '4548-4': 'hba1c',
  '39156-5': 'bmi',
}

// --- Tiny RFC-4180 CSV parser (quotes, embedded commas, CRLF) ---------------
export function parseCsv(text) {
  const rows = []
  let row = []
  let field = ''
  let inQuotes = false

  for (let i = 0; i < text.length; i++) {
    const c = text[i]
    if (inQuotes) {
      if (c === '"') {
        if (text[i + 1] === '"') {
          field += '"'
          i += 1
        } else {
          inQuotes = false
        }
      } else {
        field += c
      }
    } else if (c === '"') {
      inQuotes = true
    } else if (c === ',') {
      row.push(field)
      field = ''
    } else if (c === '\n') {
      row.push(field)
      field = ''
      if (row.length > 1 || (row.length === 1 && row[0] !== '')) rows.push(row)
      row = []
    } else if (c !== '\r') {
      field += c
    }
  }
  if (field !== '' || row.length > 0) {
    row.push(field)
    if (row.length > 1 || (row.length === 1 && row[0] !== '')) rows.push(row)
  }
  return rows
}

// --- Helpers ----------------------------------------------------------------
const toNum = (v) => {
  const n = Number(v)
  return Number.isFinite(n) ? n : null
}
const toIso = (v) => (v ? String(v).slice(0, 10) : null) // keep YYYY-MM-DD
const round1 = (x) => Math.round(x * 10) / 10
const clamp = (x, lo, hi) => Math.min(hi, Math.max(lo, x))

export function calcAge(birthdate, ref) {
  if (!birthdate) return null
  const b = new Date(birthdate)
  if (Number.isNaN(b.getTime())) return null
  let age = ref.getFullYear() - b.getFullYear()
  const m = ref.getMonth() - b.getMonth()
  if (m < 0 || (m === 0 && ref.getDate() < b.getDate())) age -= 1
  return age
}

const GENDER_MAP = { M: 'Male', F: 'Female' }

// --- Derived-layer definitions (NOT present in the Synthea source) ----------
// The SH-405 problem statement requires activity_level and
// medication_adherence; Synthea's CSV export does not contain them. These
// constants exist so nothing can silently pretend the source provided them.
export const DERIVED_FIELDS = [
  {
    field: 'activity_level',
    values: ['Sedentary', 'Light', 'Moderate', 'Active'],
    reason:
      "Synthea's CSV export has no physical-activity observations (only tobacco-smoking status and survey items about pain interfering with activity).",
    generated:
      'in the SH-405 synthetic generation layer, conditioned on age and chronic condition burden',
  },
  {
    field: 'medication_adherence',
    values: ['High', 'Medium', 'Low'],
    reason: 'Synthea models prescriptions and dispenses but not real-world adherence behavior.',
    generated:
      'in the SH-405 synthetic generation layer, conditioned on age, condition burden and payer status',
  },
]

export const FIELD_PROVENANCE = {
  patient_id: 'source',
  birth_date: 'source',
  age: 'source-derived (birth date vs reference date)',
  gender: 'source',
  conditions: 'source',
  medications: 'source',
  encounters: 'source',
  observations: 'source',
  glucose: 'source (Synthea observations: Glucose 2339-0 / Hemoglobin A1c 4548-4)',
  systolic_bp: 'source (Synthea observation LOINC 8480-6)',
  diastolic_bp: 'source (Synthea observation LOINC 8462-4)',
  pain_score: 'source (Synthea observation LOINC 72514-3)',
  date: 'source',
  activity_level: 'derived — generated by SH-405 (not in Synthea CSV export)',
  medication_adherence: 'derived — generated by SH-405 (not in Synthea CSV export)',
}

// --- Parsers per Synthea table ----------------------------------------------
function readTable(csvDir, file) {
  const raw = fs.readFileSync(path.join(csvDir, file), 'utf8')
  const rows = parseCsv(raw)
  const header = rows.shift()
  const col = (name) => header.indexOf(name)
  return { rows, col }
}

export function parsePatients(csvDir) {
  const { rows, col } = readTable(csvDir, 'patients.csv')
  const cId = col('Id')
  const cBirth = col('BIRTHDATE')
  const cDeath = col('DEATHDATE')
  const cGender = col('GENDER')
  const cFirst = col('FIRST')
  const cLast = col('LAST')
  const ref = new Date()

  return rows.map((r) => ({
    patient_id: r[cId],
    first_name: r[cFirst] || null,
    last_name: r[cLast] || null,
    birth_date: r[cBirth] || null,
    age: calcAge(r[cBirth], ref),
    gender: GENDER_MAP[r[cGender]] || r[cGender] || 'Unknown',
    deceased: Boolean(r[cDeath]),
  }))
}

export function parseConditions(csvDir) {
  const { rows, col } = readTable(csvDir, 'conditions.csv')
  const c = (n) => col(n)
  return rows.map((r) => ({
    patient_id: r[c('PATIENT')],
    start: toIso(r[c('START')]),
    stop: toIso(r[c('STOP')]) || null,
    code: r[c('CODE')],
    description: r[c('DESCRIPTION')],
  }))
}

export function parseMedications(csvDir) {
  const { rows, col } = readTable(csvDir, 'medications.csv')
  return rows.map((r) => ({
    patient_id: r[col('PATIENT')],
    start: toIso(r[col('START')]),
    stop: toIso(r[col('STOP')]) || null,
    code: r[col('CODE')],
    description: r[col('DESCRIPTION')],
    base_cost: toNum(r[col('BASE_COST')]),
  }))
}

export function parseEncounters(csvDir) {
  const { rows, col } = readTable(csvDir, 'encounters.csv')
  return rows
    .filter((r) => r[col('PATIENT')])
    .map((r) => ({
      encounter_id: r[col('Id')],
      patient_id: r[col('PATIENT')],
      start: toIso(r[col('START')]),
      class: r[col('ENCOUNTERCLASS')] || null,
      code: r[col('CODE')],
      description: r[col('REASONDESCRIPTION')] || r[col('DESCRIPTION')],
    }))
}

export function parseObservations(csvDir) {
  const { rows, col } = readTable(csvDir, 'observations.csv')
  const wanted = new Set(Object.keys(VITAL_CODES))
  return rows
    .filter((r) => wanted.has(r[col('CODE')]))
    .map((r) => ({
      patient_id: r[col('PATIENT')],
      date: toIso(r[col('DATE')]),
      code: r[col('CODE')],
      field: VITAL_CODES[r[col('CODE')]],
      value: toNum(r[col('VALUE')]),
    }))
    .filter((r) => r.value !== null)
}

// --- Pipeline orchestration --------------------------------------------------
export function ingest(csvDir, { referenceDate = new Date() } = {}) {
  const patients = parsePatients(csvDir)
  const conditions = parseConditions(csvDir)
  const medications = parseMedications(csvDir)
  const encounters = parseEncounters(csvDir)
  const observations = parseObservations(csvDir)

  const ids = new Set(patients.map((p) => p.patient_id))
  const orphans = (records) => records.filter((r) => !ids.has(r.patient_id)).length

  return {
    schema_version: CANONICAL_SCHEMA_VERSION,
    generated_at: new Date().toISOString(),
    reference_date: toIso(referenceDate.toISOString()),
    provenance: {
      generator: 'Synthea (synthetic patient generator) — all records are fabricated',
      status: 'synthetic / non-PHI',
      upstream: {
        name: 'Synthea sample dataset (small 100-patient export)',
        url: 'https://github.com/lhs-open/synthetic-data',
        license:
          'Source repo declares no license (GitHub: NOASSERTION); upstream Synthea is MIT-licensed. Data itself is synthetic and carries no PHI.',
      },
    },
    patients,
    conditions,
    medications,
    encounters,
    observations,
    integrity: {
      patients: patients.length,
      conditions: conditions.length,
      medications: medications.length,
      encounters: encounters.length,
      observations: observations.length,
      orphan_conditions: orphans(conditions),
      orphan_medications: orphans(medications),
      orphan_encounters: orphans(encounters),
      orphan_observations: orphans(observations),
    },
  }
}

// --- Source-driven distributions (used by the generator + dashboard) ---------
export function buildSourceDistributions(dataset, { referenceDate = new Date() } = {}) {
  const { patients, conditions, medications, encounters, observations } = dataset

  const ageValues = patients.map((p) => p.age).filter((a) => a !== null && a >= 0)
  const hist = (values, bins) =>
    bins.map(([label, lo, hi]) => ({
      label,
      count: values.filter((v) => v >= lo && v < hi).length,
    }))

  const ageHistogram = hist(
    ageValues,
    [
      ['0–17', 0, 18],
      ['18–35', 18, 36],
      ['36–55', 36, 56],
      ['56–75', 56, 76],
      ['76+', 76, 121],
    ],
  )

  const genderCounts = {}
  for (const p of patients) genderCounts[p.gender] = (genderCounts[p.gender] || 0) + 1

  // Diabetes status: Synthea conditions include "Diabetes" and "Prediabetes".
  const diabetesIds = new Set(
    conditions.filter((c) => /diabetes/i.test(c.description)).map((c) => c.patient_id),
  )
  const prediabetesIds = new Set(
    conditions.filter((c) => /prediabetes/i.test(c.description)).map((c) => c.patient_id),
  )

  // Mean of each normalized observation field per patient (latest wins ties by date).
  const byPatient = new Map()
  for (const o of observations) {
    if (!byPatient.has(o.patient_id)) byPatient.set(o.patient_id, {})
    const bucket = byPatient.get(o.patient_id)
    if (!bucket[o.field]) bucket[o.field] = []
    bucket[o.field].push(o)
  }

  const mean = (arr) => (arr.length ? arr.reduce((s, x) => s + x, 0) / arr.length : null)

  const perPatient = patients.map((p) => {
    const b = byPatient.get(p.patient_id) || {}
    const condCount = conditions.filter((c) => c.patient_id === p.patient_id).length
    const medCount = medications.filter((m) => m.patient_id === p.patient_id).length
    const encCount = encounters.filter((e) => e.patient_id === p.patient_id).length
    return {
      patient_id: p.patient_id,
      age: p.age,
      gender: p.gender,
      deceased: p.deceased,
      has_diabetes: diabetesIds.has(p.patient_id),
      has_prediabetes: prediabetesIds.has(p.patient_id),
      condition_count: condCount,
      medication_count: medCount,
      encounter_count: encCount,
      systolic_bp: mean((b.systolic_bp || []).map((o) => o.value)),
      diastolic_bp: mean((b.diastolic_bp || []).map((o) => o.value)),
      pain_score: mean((b.pain_score || []).map((o) => o.value)),
      glucose: mean((b.glucose || []).map((o) => o.value)),
      hba1c: mean((b.hba1c || []).map((o) => o.value)),
      bmi: mean((b.bmi || []).map((o) => o.value)),
    }
  })

  const numeric = (key) => perPatient.map((p) => p[key]).filter((v) => v !== null)
  const pearson = (xs, ys) => {
    const n = Math.min(xs.length, ys.length)
    if (n < 3) return null
    const mx = xs.reduce((s, v) => s + v, 0) / n
    const my = ys.reduce((s, v) => s + v, 0) / n
    let num = 0
    let dx = 0
    let dy = 0
    for (let i = 0; i < n; i++) {
      const a = xs[i] - mx
      const b = ys[i] - my
      num += a * b
      dx += a * a
      dy += b * b
    }
    const den = Math.sqrt(dx * dy)
    return den === 0 ? null : round1(num / den)
  }

  const pairs = {}
  const corr = (a, b) => {
    const key = [a, b].sort().join('~')
    if (!(key in pairs)) {
      const rowsWithBoth = perPatient.filter((p) => p[a] !== null && p[b] !== null)
      pairs[key] = pearson(rowsWithBoth.map((r) => r[a]), rowsWithBoth.map((r) => r[b]))
    }
    return pairs[key]
  }

  return {
    reference_date: toIso(referenceDate.toISOString()),
    n_patients: patients.length,
    age_histogram: ageHistogram,
    gender_counts: genderCounts,
    diabetes: {
      diagnosed: diabetesIds.size,
      prediabetes: prediabetesIds.size,
      pct: round1((diabetesIds.size / Math.max(1, patients.length)) * 100),
    },
    means: {
      age: round1(mean(ageValues)),
      systolic_bp: round1(mean(numeric('systolic_bp'))),
      diastolic_bp: round1(mean(numeric('diastolic_bp'))),
      pain_score: round1(mean(numeric('pain_score'))),
      glucose: round1(mean(numeric('glucose'))),
      hba1c: round1(mean(numeric('hba1c'))),
      bmi: round1(mean(numeric('bmi'))),
    },
    condition_burden: {
      avg_conditions_per_patient: round1(mean(perPatient.map((p) => p.condition_count))),
      avg_medications_per_patient: round1(mean(perPatient.map((p) => p.medication_count))),
      avg_encounters_per_patient: round1(mean(perPatient.map((p) => p.encounter_count))),
    },
    correlations: {
      // Relationship targets required by the SH-405 problem statement.
      'age~systolic_bp': corr('age', 'systolic_bp'),
      'age~diastolic_bp': corr('age', 'diastolic_bp'),
      'age~condition_count': corr('age', 'condition_count'),
      'hba1c~glucose': corr('hba1c', 'glucose'),
      'pain_score~condition_count': corr('pain_score', 'condition_count'),
      'glucose~condition_count': corr('glucose', 'condition_count'),
      'bmi~glucose': corr('bmi', 'glucose'),
    },
    per_patient: perPatient,
  }
}

// --- Longitudinal records (one row per patient-date) ------------------------
export function buildLongitudinal(dataset) {
  const byKey = new Map()
  const touch = (pid, date) => {
    const key = `${pid}|${date}`
    if (!byKey.has(key)) byKey.set(key, { patient_id: pid, date })
    return byKey.get(key)
  }

  for (const o of dataset.observations) {
    const row = touch(o.patient_id, o.date)
    row[o.field] = o.value
  }
  for (const e of dataset.encounters) {
    if (!e.start) continue
    touch(e.patient_id, e.start).encounter = e.description || e.class || e.code
  }
  for (const m of dataset.medications) {
    if (!m.start) continue
    const row = touch(m.patient_id, m.start)
    if (!row.medications) row.medications = []
    row.medications.push(m.description)
  }
  for (const c of dataset.conditions) {
    if (!c.start) continue
    const row = touch(c.patient_id, c.start)
    if (!row.conditions) row.conditions = []
    row.conditions.push(c.description)
  }

  const records = [...byKey.values()].sort(
    (a, b) => (a.date < b.date ? -1 : a.date > b.date ? 1 : a.patient_id.localeCompare(b.patient_id)),
  )
  return { count: records.length, records }
}

export { round1, clamp, toIso }
